[project]
name = "paper-wiki"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "chromadb>=1.5.9",
    "mineru>=4.0.4",
    "nougat>=0.3.3",
    "nougat-ocr>=0.1.17",
]

[project.scripts]
paper-wiki = "paper_wiki:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
